### ISSUE TITLE
Error: Currently can only observe point queries and orderBy/limit queries

### ISSUE THREAD

**Issue by bobbigmac** [Slava/meteor-rethinkdb-demo#1]
Project not currently running as is.

```
Exception from sub data id hpfDb29J8J8rr99Xt Error: Currently can only observe point queries and orderBy/limit queries. For example: Table.get(id); Table.orderBy({ index: 'id' }).limit(4).
```

To replicate, install rethinkdb, run, create a table called "cities", clone demo repo and run `meteor`.

The publish function seems to be returning an orderBy/limit query as required. Seems to be some mismatch between what is documented to work, and what works (so far I can't find any returned cursor that the package will accept). I'm new to rethink though so haven't had a chance for a good poke around yet.

Full trace

```
=> App running at: http://localhost:3000/
I20151117-08:23:16.360(0)? Exception from sub data id hpfDb29J8J8rr99Xt Error: Currently can only observe point queries and orderBy/limit queries. For example: Table.get(id); Table.orderBy({ index: 'id' }).limit(4).
I20151117-08:23:16.360(0)?     at Object.Future.wait (/home/bobbigmac/.meteor/packages/meteor-tool/.1.1.3.60vz0v++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:395:16)
I20151117-08:23:16.361(0)?     at Limit.observe (packages/simple:rethink/rethink.js:243:1)
I20151117-08:23:16.361(0)?     at Function.Rethink.Table._publishCursor (packages/simple:rethink/rethink.js:274:1)
I20151117-08:23:16.361(0)?     at Limit._publishCursor (packages/simple:rethink/rethink.js:265:1)
I20151117-08:23:16.361(0)?     at [object Object]._.extend._runHandler (packages/ddp/livedata_server.js:986:1)
I20151117-08:23:16.361(0)?     at [object Object]._.extend._startSubscription (packages/ddp/livedata_server.js:769:1)
I20151117-08:23:16.361(0)?     at [object Object]._.extend.protocol_handlers.sub (packages/ddp/livedata_server.js:582:1)
I20151117-08:23:16.361(0)?     at packages/ddp/livedata_server.js:546:1
I20151117-08:23:16.361(0)?     - - - - -
I20151117-08:23:16.361(0)?     at packages/simple:rethink/rethink.js:203:1
I20151117-08:23:16.361(0)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
I20151117-08:23:16.361(0)?     at packages/meteor/dynamics_nodejs.js:121:1
I20151117-08:23:16.362(0)?     at /home/bobbigmac/.meteor/packages/simple_rethink/.0.0.1.1fkpato++os+web.browser+web.cordova/npm/node_modules/rethinkdb/cursor.js:262:24
I20151117-08:23:16.362(0)?     at OrderByLimitFeed.IterableResult._handleRow (/home/bobbigmac/.meteor/packages/simple_rethink/.0.0.1.1fkpato++os+web.browser+web.cordova/npm/node_modules/rethinkdb/cursor.js:116:12)
```

Various other failing returns

``` javascript
  Meteor.publish("data", function () {
    console.log(Cities.orderBy({ index: 'id' }).count().run(), 'cities') // 5 'cities'
    return Cities.get('f3138aec-f02b-4412-9308-deb54ff8ee57');
    return Cities.orderBy(r.desc('population')).limit(100);
    return r.table('cities').orderBy(r.desc('population')).limit(100);
    return Cities
      .filter(r.row("population").gt(20000000))
      .orderBy({ index: 'id' })
      .limit(100);
  });
```

**Comment by lorensr** [comment]
I can reproduce using rethink `v2.2.0`. Don't know why it's happening. It works fine using rethink `v2.0.1`.

**Comment by bobbigmac** [comment]
Fixed by https://github.com/Slava/meteor-rethinkdb/pull/26
